name: Deploy React storybook to IBM Cloud

on:
  push:
    tags:
      # Matches tags that have the shape `vX.Y.Z`. This will also match tags
      # with a preid, for example `vX.Y.Z-rc.0`. Reference:
      # https://help.github.com/en/articles/workflow-syntax-for-github-actions#onpushpull_requesttagsbranches
      - 'v*.*.*'

jobs:
  build:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@master

      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          version: 10.x

      - name: Install dependencies
        run: yarn install --offline

      - name: Build project
        run: yarn build

      - name: Install ibmcloud CLI
        run: curl -fsSL https://clis.cloud.ibm.com/install/osx | sh

      - name: Login to IBM Cloud
        env:
          CLOUD_API_KEY: ${{ secrets.CLOUD_API_KEY}}
        run: |
          ibmcloud login \
          -a 'https://cloud.ibm.com' \
          -u 'apikey' \
          -p "$CLOUD_API_KEY" \
          -o 'carbon-design-system' \
          -s 'production' \
          -r 'us-south'

      - name: Install IBM Cloud plugins
        run: |
          ibmcloud cf add-plugin-repo CF-Community https://plugins.cloudfoundry.org
          ibmcloud cf install-plugin blue-green-deploy -f -r CF-Community

      - name: Deploy React storybook
        run: |
          cd packages/react
          yarn build-storybook
          ibmcloud cf blue-green-deploy carbon-storybook \
            -f manifest.yml \
            --delete-old-apps
